import McCulloch26_1.Cor_3_3_A4
import McCulloch26_1.Thm_2_3_TwoEnds

/-!
# Theorem 2.3 instance at $k = 3$: $A_4$ has no $(2,3,2)$ factorization

Completes the excluded case of Corollary 3.3 of McCulloch26-1 (tex lines
220-229): "except for $(2,3,2)$, for which no 3-factorization exists", which
the paper derives from Theorem `thm1` (tex lines 128-142). We instantiate the
generalized `no_factorization_with_small_ends` with $G = A_4$ and $N = V_4$.

The two abstract properties demanded at tex line 128 are verified concretely
inside `Perm (Fin 4)`:
* even-order elements of $A_4$ land in $V_4$ (tex line 137: "the only even
  order elements of $G$ are the elements of $N$"): a power of even order
  yields an involution, every involution of $A_4$ is one of the three double
  transpositions, and anything in $A_4$ commuting with a double transposition
  lies in $V_4$;
* conjugation reaches every nonidentity element of $V_4$: conjugation by the
  cycle $(0\,1\,2)$ permutes the three double transpositions cyclically (tex
  line 139).

Source:
/home/chz/src/gamskil/docs/arxiv/2607.20569v3/Some_Answers_Factorization.tex
lines 128-142 (theorem `thm1` and its printed proof), lines 220-229 (final
corollary).
-/

open Equiv Equiv.Perm Subgroup Finset

namespace McCulloch26_1.Cor33

/-! ### The 3-cycle $(0\,1\,2)$ -/

/-- The cycle $(0\,1\,2)$ (tex line 129: complement generated by a primitive
element, whose conjugation action permutes the nonidentity kernel elements
cyclically). -/
def cyc : Perm (Fin 4) := swap 1 2 * swap 0 2

theorem cyc_mul_dt1 : cyc * dt1 = dt3 * cyc := perm_ext4 rfl rfl rfl rfl
theorem cyc_mul_dt2 : cyc * dt2 = dt1 * cyc := perm_ext4 rfl rfl rfl rfl
theorem cyc_mul_dt3 : cyc * dt3 = dt2 * cyc := perm_ext4 rfl rfl rfl rfl

theorem mem_a4_cyc : cyc ∈ alternatingGroup (Fin 4) := by
  rw [mem_alternatingGroup]
  have h : cyc = swap 1 2 * swap 0 2 := rfl
  rw [h, sign_mul, sign_swap (show (1 : Fin 4) ≠ 2 by decide),
    sign_swap (show (0 : Fin 4) ≠ 2 by decide)]
  norm_num

theorem conj_cyc_dt1 : cyc * dt1 * cyc⁻¹ = dt3 := by rw [cyc_mul_dt1]; group
theorem conj_cyc_dt2 : cyc * dt2 * cyc⁻¹ = dt1 := by rw [cyc_mul_dt2]; group
theorem conj_cyc_dt3 : cyc * dt3 * cyc⁻¹ = dt2 := by rw [cyc_mul_dt3]; group

theorem conj_cyc_inv_dt1 : cyc⁻¹ * dt1 * cyc = dt2 := by
  calc cyc⁻¹ * dt1 * cyc
      = cyc⁻¹ * (cyc * dt2 * cyc⁻¹) * cyc := by rw [conj_cyc_dt2]
    _ = dt2 := by group

theorem conj_cyc_inv_dt2 : cyc⁻¹ * dt2 * cyc = dt3 := by
  calc cyc⁻¹ * dt2 * cyc
      = cyc⁻¹ * (cyc * dt3 * cyc⁻¹) * cyc := by rw [conj_cyc_dt3]
    _ = dt3 := by group

theorem conj_cyc_inv_dt3 : cyc⁻¹ * dt3 * cyc = dt1 := by
  calc cyc⁻¹ * dt3 * cyc
      = cyc⁻¹ * (cyc * dt1 * cyc⁻¹) * cyc := by rw [conj_cyc_dt1]
    _ = dt1 := by group

theorem mem_a4_cyc_inv : (cyc⁻¹ : Perm (Fin 4)) ∈ alternatingGroup (Fin 4) := by
  rw [mem_alternatingGroup, map_inv, mem_alternatingGroup.mp mem_a4_cyc]
  norm_num

theorem mem_a4_cyc2inv :
    ((cyc⁻¹ : Perm (Fin 4)) * cyc⁻¹) ∈ alternatingGroup (Fin 4) := by
  rw [mem_alternatingGroup, sign_mul, mem_alternatingGroup.mp mem_a4_cyc_inv]
  norm_num

/-- Conjugation transport through the cycle: $c^{-1} w c$ stays in $V_4$. -/
theorem mem_V4_conj_cyc {w z : Perm (Fin 4)} (hw : w ∈ V4)
    (hz : z = cyc⁻¹ * w * cyc) : z ∈ V4 := by
  subst hz
  rcases mem_V4.mp hw with rfl | rfl | rfl | rfl
  · simp
  · rw [conj_cyc_inv_dt1]
    exact mem_V4.2 (Or.inr (Or.inr (Or.inl rfl)))
  · rw [conj_cyc_inv_dt2]
    exact mem_V4.2 (Or.inr (Or.inr (Or.inr rfl)))
  · rw [conj_cyc_inv_dt3]
    exact mem_V4.2 (Or.inr (Or.inl rfl))

/-! ### Four-point bookkeeping -/

private theorem cov4 {a b c e : Fin 4} (hab : a ≠ b) (hac : a ≠ c) (hae : a ≠ e)
    (hbc : b ≠ c) (hbd : b ≠ e) (hce : c ≠ e) :
    ∀ w : Fin 4, w = a ∨ w = b ∨ w = c ∨ w = e := by
  intro w
  have h0 := w.isLt; have h1 := a.isLt; have h2 := b.isLt
  have h3 := c.isLt; have h4 := e.isLt
  have hv : (w : ℕ) = (a : ℕ) ∨ (w : ℕ) = (b : ℕ) ∨ (w : ℕ) = (c : ℕ) ∨
      (w : ℕ) = (e : ℕ) := by omega
  rcases hv with h | h | h | h
  · exact Or.inl (Fin.ext h)
  · exact Or.inr (Or.inl (Fin.ext h))
  · exact Or.inr (Or.inr (Or.inl (Fin.ext h)))
  · exact Or.inr (Or.inr (Or.inr (Fin.ext h)))

private theorem quad_cell (y : Perm (Fin 4)) {i j k l : Fin 4}
    (hik : i ≠ k) (hil : i ≠ l) (hjk : j ≠ k) (hjl : j ≠ l)
    (hyi : y i = j) (hyj : y j = i) (hyk : y k = l) (hyl : y l = k)
    (w : Fin 4) (hw : w = i ∨ w = j ∨ w = k ∨ w = l) :
    y w = (swap i j * swap k l) w := by
  rcases hw with h | h | h | h
  · rw [h, hyi]
    simp only [Perm.coe_mul, Function.comp_apply]
    rw [Equiv.swap_apply_of_ne_of_ne hik hil, Equiv.swap_apply_left]
  · rw [h, hyj]
    simp only [Perm.coe_mul, Function.comp_apply]
    rw [Equiv.swap_apply_of_ne_of_ne hjk hjl, Equiv.swap_apply_right]
  · rw [h, hyk]
    simp only [Perm.coe_mul, Function.comp_apply]
    rw [Equiv.swap_apply_left,
      Equiv.swap_apply_of_ne_of_ne (Ne.symm hil) (Ne.symm hjl)]
  · rw [h, hyl]
    simp only [Perm.coe_mul, Function.comp_apply]
    rw [Equiv.swap_apply_right,
      Equiv.swap_apply_of_ne_of_ne (Ne.symm hik) (Ne.symm hjk)]

private theorem eq_swap_mul_of_quad {y : Perm (Fin 4)} {i j k l : Fin 4}
    (hik : i ≠ k) (hil : i ≠ l) (hjk : j ≠ k) (hjl : j ≠ l)
    (hyi : y i = j) (hyj : y j = i) (hyk : y k = l) (hyl : y l = k)
    (hcov : ∀ w : Fin 4, w = i ∨ w = j ∨ w = k ∨ w = l) :
    y = swap i j * swap k l :=
  perm_ext4 (quad_cell y hik hil hjk hjl hyi hyj hyk hyl 0 (hcov 0))
    (quad_cell y hik hil hjk hjl hyi hyj hyk hyl 1 (hcov 1))
    (quad_cell y hik hil hjk hjl hyi hyj hyk hyl 2 (hcov 2))
    (quad_cell y hik hil hjk hjl hyi hyj hyk hyl 3 (hcov 3))

private theorem trans_cell (y : Perm (Fin 4)) {i j k m : Fin 4}
    (hik : i ≠ k) (hjk : j ≠ k) (him : i ≠ m) (hjm : j ≠ m) (_hkm : k ≠ m)
    (hyi : y i = j) (hyj : y j = i) (hyk : y k = k) (hym : y m = m)
    (w : Fin 4) (hw : w = i ∨ w = j ∨ w = k ∨ w = m) :
    y w = (swap i j) w := by
  rcases hw with h | h | h | h
  · rw [h, hyi, Equiv.swap_apply_left]
  · rw [h, hyj, Equiv.swap_apply_right]
  · rw [h, hyk, Equiv.swap_apply_of_ne_of_ne (Ne.symm hik) (Ne.symm hjk)]
  · rw [h, hym, Equiv.swap_apply_of_ne_of_ne (Ne.symm him) (Ne.symm hjm)]

private theorem eq_swap_of_trans {y : Perm (Fin 4)} {i j k m : Fin 4}
    (hik : i ≠ k) (hjk : j ≠ k) (him : i ≠ m) (hjm : j ≠ m) (hkm : k ≠ m)
    (hyi : y i = j) (hyj : y j = i) (hyk : y k = k) (hym : y m = m)
    (hcov : ∀ w : Fin 4, w = i ∨ w = j ∨ w = k ∨ w = m) :
    y = swap i j :=
  perm_ext4 (trans_cell y hik hjk him hjm hkm hyi hyj hyk hym 0 (hcov 0))
    (trans_cell y hik hjk him hjm hkm hyi hyj hyk hym 1 (hcov 1))
    (trans_cell y hik hjk him hjm hkm hyi hyj hyk hym 2 (hcov 2))
    (trans_cell y hik hjk him hjm hkm hyi hyj hyk hym 3 (hcov 3))

private theorem quad_swap_is_dt {i j k l : Fin 4}
    (hab : i ≠ j) (hac : i ≠ k) (had : i ≠ l) (hbc : j ≠ k) (hbd : j ≠ l)
    (hcd : k ≠ l) :
    (swap i j * swap k l : Perm (Fin 4)) = dt1 ∨
      (swap i j * swap k l : Perm (Fin 4)) = dt2 ∨
      (swap i j * swap k l : Perm (Fin 4)) = dt3 := by
  fin_cases i <;> fin_cases j <;> fin_cases k <;> fin_cases l <;>
    first
      | (exfalso; omega)
      | exact Or.inl (perm_ext4 rfl rfl rfl rfl)
      | exact Or.inr (Or.inl (perm_ext4 rfl rfl rfl rfl))
      | exact Or.inr (Or.inr (perm_ext4 rfl rfl rfl rfl))

/-! ### Every involution of $A_4$ is a double transposition -/

/-- Tex line 137: an involution of $A_4$ lies in $V_4$: it swaps one pair of
points and pairs up the remaining two (double transposition) rather than
fixing them (transposition, odd sign). -/
theorem involution_mem_V4 {y : Perm (Fin 4)} (hyA : y ∈ alternatingGroup (Fin 4))
    (hy2 : y * y = 1) (hy1 : y ≠ 1) : y ∈ V4 := by
  have hne1 : ∃ i : Fin 4, y i ≠ i := by
    by_contra hall
    push_neg at hall
    exact hy1 (perm_ext4
      (show y 0 = (1 : Perm (Fin 4)) 0 from hall 0)
      (show y 1 = (1 : Perm (Fin 4)) 1 from hall 1)
      (show y 2 = (1 : Perm (Fin 4)) 2 from hall 2)
      (show y 3 = (1 : Perm (Fin 4)) 3 from hall 3))
  obtain ⟨i, hi⟩ := hne1
  have hii : y i ≠ i := hi
  obtain ⟨j, hjdef⟩ : ∃ j, y i = j := ⟨y i, rfl⟩
  rw [hjdef] at hii
  have hji : j ≠ i := hii
  have hyj : y j = i := by
    rw [← hjdef]
    have h := congrArg (fun σ : Perm (Fin 4) => σ i) hy2
    simpa using h
  have hinj : Function.Injective (y : Fin 4 → Fin 4) := y.bijective.1
  obtain ⟨k, hki, hkj⟩ : ∃ k : Fin 4, k ≠ i ∧ k ≠ j := by
    fin_cases i <;> fin_cases j <;>
      first
        | exact ⟨⟨0, by decide⟩, by decide, by decide⟩
        | exact ⟨⟨1, by decide⟩, by decide, by decide⟩
        | exact ⟨⟨2, by decide⟩, by decide, by decide⟩
  obtain ⟨l, hldef⟩ : ∃ l, y k = l := ⟨y k, rfl⟩
  have hyy : y l = k := by
    rw [← hldef]
    have h := congrArg (fun σ : Perm (Fin 4) => σ k) hy2
    simpa using h
  by_cases hlk : l = k
  · exfalso
    rw [hlk] at hldef
    obtain ⟨m, hmi, hmj, hmk⟩ : ∃ m : Fin 4, m ≠ i ∧ m ≠ j ∧ m ≠ k := by
      fin_cases i <;> fin_cases j <;> fin_cases k <;>
        first
          | exact ⟨⟨0, by decide⟩, by decide, by decide, by decide⟩
          | exact ⟨⟨1, by decide⟩, by decide, by decide, by decide⟩
          | exact ⟨⟨2, by decide⟩, by decide, by decide, by decide⟩
          | exact ⟨⟨3, by decide⟩, by decide, by decide, by decide⟩
    have hcov : ∀ w : Fin 4, w = i ∨ w = j ∨ w = k ∨ w = m :=
      cov4 (Ne.symm hji) (Ne.symm hki) (Ne.symm hmi) (Ne.symm hkj) (Ne.symm hmj)
        (Ne.symm hmk)
    have hym : y m = m := by
      rcases hcov (y m) with h | h | h | h
      · exact absurd (hinj (h.trans hyj.symm)) hmj
      · exact absurd (hinj (h.trans hjdef.symm)) hmi
      · exact absurd ((hinj (h.trans hyy.symm)).trans hlk) hmk
      · exact h
    have hyswap : y = swap i j :=
      eq_swap_of_trans (Ne.symm hki) (Ne.symm hkj) (Ne.symm hmi) (Ne.symm hmj)
        (Ne.symm hmk) hjdef hyj hldef hym hcov
    have hs : sign y = 1 := mem_alternatingGroup.mp hyA
    rw [hyswap, sign_swap (Ne.symm hji)] at hs
    norm_num at hs
  · have hli : l ≠ i := by
      intro hc
      rw [hc] at hldef
      exact hkj (hinj (hldef.trans hyj.symm))
    have hlj : l ≠ j := by
      intro hc
      rw [hc] at hldef
      exact hki (hinj (hldef.trans hjdef.symm))
    have hcov : ∀ w : Fin 4, w = i ∨ w = j ∨ w = k ∨ w = l :=
      cov4 (Ne.symm hji) (Ne.symm hki) (Ne.symm hli) (Ne.symm hkj) (Ne.symm hlj)
        (Ne.symm hlk)
    have hq : y = swap i j * swap k l :=
      eq_swap_mul_of_quad (Ne.symm hki) (Ne.symm hli) (Ne.symm hkj) (Ne.symm hlj)
        hjdef hyj hldef hyy hcov
    rcases quad_swap_is_dt (Ne.symm hji) (Ne.symm hki) (Ne.symm hli) (Ne.symm hkj) (Ne.symm hlj)
        (Ne.symm hlk)
      with h | h | h
    · exact mem_V4.2 (Or.inr (Or.inl (hq.trans h)))
    · exact mem_V4.2 (Or.inr (Or.inr (Or.inl (hq.trans h))))
    · exact mem_V4.2 (Or.inr (Or.inr (Or.inr (hq.trans h))))

/-! ### Commuting with a double transposition inside $A_4$ -/

/-- If $z \in A_4$ commutes with an element acting as the paired swaps
$p \leftrightarrow q$, $r \leftrightarrow s$, then $z \in V_4$: fixing or
swapping a pair keeps $z$ inside $V_4$-generated cases, swapping both pairs
is itself a double transposition, and crossing the pairs yields a 4-cycle of
odd sign. -/
private theorem mem_V4_of_commute_aux (z d : Perm (Fin 4)) {p q r s : Fin 4}
    (hpq : p ≠ q) (hpr : p ≠ r) (hps : p ≠ s) (hqr : q ≠ r) (hqs : q ≠ s)
    (hrs : r ≠ s)
    (hdp : d p = q) (hdq : d q = p) (hdr : d r = s) (hds : d s = r)
    (hcov : ∀ w : Fin 4, w = p ∨ w = q ∨ w = r ∨ w = s)
    (hc : z * d = d * z) (hzA : z ∈ alternatingGroup (Fin 4)) :
    z ∈ V4 := by
  have key : ∀ w : Fin 4, z (d w) = d (z w) := by
    intro w
    have h := congrArg (fun σ : Perm (Fin 4) => (σ : Fin 4 → Fin 4) w) hc
    simpa using h
  have hinj : Function.Injective (z : Fin 4 → Fin 4) := z.bijective.1
  have hs : sign z = 1 := mem_alternatingGroup.mp hzA
  obtain ⟨t, ht⟩ : ∃ t, z p = t := ⟨z p, rfl⟩
  rcases hcov t with ht0 | ht0 | ht0 | ht0
  · rw [ht0] at ht
    -- z p = p, hence z q = q
    have k1 : z q = q := by
      have h := key p
      rw [hdp, ht, hdp] at h
      exact h
    obtain ⟨u, hu⟩ : ∃ u, z r = u := ⟨z r, rfl⟩
    rcases hcov u with hu0 | hu0 | hu0 | hu0
    · rw [hu0] at hu
      exfalso; apply hpr; apply hinj; rw [ht, hu]
    · rw [hu0] at hu
      exfalso; apply hqr; apply hinj; rw [k1, hu]
    · rw [hu0] at hu
      -- z r = r: also z s = s, so z = 1
      have hzs : z s = s := by
        have h := key r
        rw [hdr, hu, hdr] at h
        exact h
      have cell : ∀ w : Fin 4, z w = (1 : Perm (Fin 4)) w := by
        intro w
        rcases hcov w with h | h | h | h
        · rw [h, ht]; rfl
        · rw [h, k1]; rfl
        · rw [h, hu]; rfl
        · rw [h, hzs]; rfl
      exact mem_V4.2 (Or.inl (perm_ext4 (cell 0) (cell 1) (cell 2) (cell 3)))
    · rw [hu0] at hu
      -- z r = s: then z s = r, so z = swap r s, of odd sign
      have hzs : z s = r := by
        have h := key r
        rw [hdr, hu, hds] at h
        exact h
      exfalso
      have hzswap : z = swap r s :=
        eq_swap_of_trans (Ne.symm hpr) (Ne.symm hps) (Ne.symm hqr) (Ne.symm hqs)
          hpq hu hzs ht k1
          (by intro w
              rcases cov4 hpq hpr hps hqr hqs hrs w with h' | h' | h' | h'
              · exact Or.inr (Or.inr (Or.inl h'))
              · exact Or.inr (Or.inr (Or.inr h'))
              · exact Or.inl h'
              · exact Or.inr (Or.inl h'))
      rw [hzswap, sign_swap hrs] at hs
      norm_num at hs
  · rw [ht0] at ht
    -- z p = q, hence z q = p
    have k1 : z q = p := by
      have h := key p
      rw [hdp, ht, hdq] at h
      exact h
    obtain ⟨u, hu⟩ : ∃ u, z r = u := ⟨z r, rfl⟩
    rcases hcov u with hu0 | hu0 | hu0 | hu0
    · rw [hu0] at hu
      exfalso; apply hqr; apply hinj; rw [k1, hu]
    · rw [hu0] at hu
      exfalso; apply hpr; apply hinj; rw [ht, hu]
    · rw [hu0] at hu
      -- z r = r: then z s = s, so z = swap p q, of odd sign
      have hzs : z s = s := by
        have h := key r
        rw [hdr, hu, hdr] at h
        exact h
      exfalso
      have hzswap : z = swap p q :=
        eq_swap_of_trans hpr hqr hps hqs hrs ht k1 hu hzs hcov
      rw [hzswap, sign_swap hpq] at hs
      norm_num at hs
    · rw [hu0] at hu
      -- z r = s: then z s = r: z is itself the double transposition
      have hzs : z s = r := by
        have h := key r
        rw [hdr, hu, hds] at h
        exact h
      have hzdt : z = swap p q * swap r s :=
        eq_swap_mul_of_quad hpr hps hqr hqs ht k1 hu hzs hcov
      rcases quad_swap_is_dt hpq hpr hps hqr hqs hrs with h | h | h
      · exact mem_V4.2 (Or.inr (Or.inl (hzdt.trans h)))
      · exact mem_V4.2 (Or.inr (Or.inr (Or.inl (hzdt.trans h))))
      · exact mem_V4.2 (Or.inr (Or.inr (Or.inr (hzdt.trans h))))
  · rw [ht0] at ht
    -- z p = r, hence z q = s
    have k1 : z q = s := by
      have h := key p
      rw [hdp, ht, hdr] at h
      exact h
    obtain ⟨u, hu⟩ : ∃ u, z r = u := ⟨z r, rfl⟩
    rcases hcov u with hu0 | hu0 | hu0 | hu0
    · rw [hu0] at hu
      -- z r = p: crossing once, z = swap p r * swap q s ∈ V4
      have hzs : z s = q := by
        have h := key r
        rw [hdr, hu, hdp] at h
        exact h
      have hzcross : z = swap p r * swap q s :=
        eq_swap_mul_of_quad hpq hps (Ne.symm hqr) hrs ht hu k1 hzs
          (by intro w
              rcases cov4 hpq hpr hps hqr hqs hrs w with h' | h' | h' | h'
              · exact Or.inl h'
              · exact Or.inr (Or.inr (Or.inl h'))
              · exact Or.inr (Or.inl h')
              · exact Or.inr (Or.inr (Or.inr h')))
      rcases quad_swap_is_dt hpr hpq hps (Ne.symm hqr) hrs hqs with h | h | h
      · rw [hzcross]; exact mem_V4.2 (Or.inr (Or.inl h))
      · rw [hzcross]; exact mem_V4.2 (Or.inr (Or.inr (Or.inl h)))
      · rw [hzcross]; exact mem_V4.2 (Or.inr (Or.inr (Or.inr h)))
    · rw [hu0] at hu
      -- z r = q: 4-cycle p → r → q → s → p, of odd sign
      have hzs : z s = p := by
        have h := key r
        rw [hdr, hu, hdq] at h
        exact h
      exfalso
      have hcell : ∀ w : Fin 4, z w = (swap p s * swap p q * swap p r) w := by
        intro w
        rcases hcov w with h | h | h | h
        · rw [h, ht]
          simp only [Perm.coe_mul, Function.comp_apply]
          rw [Equiv.swap_apply_left,
            Equiv.swap_apply_of_ne_of_ne (Ne.symm hpr) (Ne.symm hqr),
            Equiv.swap_apply_of_ne_of_ne (Ne.symm hpr) hrs]
        · rw [h, k1]
          simp only [Perm.coe_mul, Function.comp_apply]
          rw [Equiv.swap_apply_of_ne_of_ne (Ne.symm hpq) hqr,
            Equiv.swap_apply_right,
            Equiv.swap_apply_left]
        · rw [h, hu]
          simp only [Perm.coe_mul, Function.comp_apply]
          rw [Equiv.swap_apply_right,
            Equiv.swap_apply_left,
            Equiv.swap_apply_of_ne_of_ne (Ne.symm hpq) hqs]
        · rw [h, hzs]
          simp only [Perm.coe_mul, Function.comp_apply]
          rw [Equiv.swap_apply_of_ne_of_ne (Ne.symm hps) (Ne.symm hrs),
            Equiv.swap_apply_of_ne_of_ne (Ne.symm hps) (Ne.symm hqs),
            Equiv.swap_apply_right]
      have hzcyc : z = swap p s * swap p q * swap p r :=
        perm_ext4 (hcell 0) (hcell 1) (hcell 2) (hcell 3)
      rw [hzcyc, sign_mul, sign_mul, sign_swap hps, sign_swap hpq,
        sign_swap hpr] at hs
      norm_num at hs
    · rw [hu0] at hu
      exfalso; apply hpr; apply hinj; rw [ht, hu]
    · rw [hu0] at hu
      exfalso; apply hqr; apply hinj; rw [k1, hu]
  · rw [ht0] at ht
    -- z p = s, hence z q = r
    have k1 : z q = r := by
      have h := key p
      rw [hdp, ht, hds] at h
      exact h
    obtain ⟨u, hu⟩ : ∃ u, z r = u := ⟨z r, rfl⟩
    rcases hcov u with hu0 | hu0 | hu0 | hu0
    · rw [hu0] at hu
      -- z r = p: z is the 4-cycle p → s → q → r → p, of odd sign
      have hzs : z s = q := by
        have h := key r
        rw [hdr, hu, hdp] at h
        exact h
      exfalso
      have hcell : ∀ w : Fin 4, z w = (swap p r * swap p q * swap p s) w := by
        intro w
        rcases hcov w with h | h | h | h
        · rw [h, ht]
          simp only [Perm.coe_mul, Function.comp_apply]
          rw [Equiv.swap_apply_left,
            Equiv.swap_apply_of_ne_of_ne (Ne.symm hps) (Ne.symm hqs),
            Equiv.swap_apply_of_ne_of_ne (Ne.symm hps) (Ne.symm hrs)]
        · rw [h, k1]
          simp only [Perm.coe_mul, Function.comp_apply]
          rw [Equiv.swap_apply_of_ne_of_ne (Ne.symm hpq) hqs,
            Equiv.swap_apply_right,
            Equiv.swap_apply_left]
        · rw [h, hu]
          simp only [Perm.coe_mul, Function.comp_apply]
          rw [Equiv.swap_apply_of_ne_of_ne (Ne.symm hpr) hrs,
            Equiv.swap_apply_of_ne_of_ne (Ne.symm hpr) (Ne.symm hqr),
            Equiv.swap_apply_right]
        · rw [h, hzs]
          simp only [Perm.coe_mul, Function.comp_apply]
          rw [Equiv.swap_apply_right,
            Equiv.swap_apply_left,
            Equiv.swap_apply_of_ne_of_ne (Ne.symm hpq) hqr]
      have hzcyc : z = swap p r * swap p q * swap p s :=
        perm_ext4 (hcell 0) (hcell 1) (hcell 2) (hcell 3)
      rw [hzcyc, sign_mul, sign_mul, sign_swap hpr, sign_swap hpq,
        sign_swap hps] at hs
      norm_num at hs
    · rw [hu0] at hu
      -- z r = q: z s = p: same double transposition (p s)(q r)
      have hzs : z s = p := by
        have h := key r
        rw [hdr, hu, hdq] at h
        exact h
      have hzcross : z = swap p s * swap q r :=
        eq_swap_mul_of_quad hpq hpr (Ne.symm hqs) (Ne.symm hrs) ht hzs k1 hu
          (by intro w
              rcases cov4 hpq hpr hps hqr hqs hrs w with h' | h' | h' | h'
              · exact Or.inl h'
              · exact Or.inr (Or.inr (Or.inl h'))
              · exact Or.inr (Or.inr (Or.inr h'))
              · exact Or.inr (Or.inl h'))
      rcases quad_swap_is_dt hps hpq hpr (Ne.symm hqs) (Ne.symm hrs) hqr
        with h | h | h
      · rw [hzcross]; exact mem_V4.2 (Or.inr (Or.inl h))
      · rw [hzcross]; exact mem_V4.2 (Or.inr (Or.inr (Or.inl h)))
      · rw [hzcross]; exact mem_V4.2 (Or.inr (Or.inr (Or.inr h)))
    · rw [hu0] at hu
      exfalso; apply hqr; apply hinj; rw [k1, hu]
    · rw [hu0] at hu
      exfalso; apply hpr; apply hinj; rw [ht, hu]

/-- Tex line 137: an element of $A_4$ commuting with a nontrivial element of
$V_4$ lies in $V_4$. -/
theorem mem_V4_of_commute {z : Perm (Fin 4)} (hzA : z ∈ alternatingGroup (Fin 4))
    {d : Perm (Fin 4)} (hdV : d ∈ V4) (hd1 : d ≠ 1) (hc : z * d = d * z) :
    z ∈ V4 := by
  rcases mem_V4.mp hdV with rfl | rfl | rfl | rfl
  · exact absurd rfl hd1
  · exact mem_V4_of_commute_aux z dt1 (p := 0) (q := 1) (r := 2) (s := 3)
      (by decide) (by decide) (by decide)
      (by decide) (by decide) (by decide) rfl rfl rfl rfl
      (cov4 (by decide) (by decide) (by decide) (by decide) (by decide)
        (by decide)) hc hzA
  · exact mem_V4_of_commute_aux z dt2 (p := 0) (q := 2) (r := 1) (s := 3)
      (by decide) (by decide) (by decide)
      (by decide) (by decide) (by decide) rfl rfl rfl rfl
      (cov4 (by decide) (by decide) (by decide) (by decide) (by decide)
        (by decide)) hc hzA
  · exact mem_V4_of_commute_aux z dt3 (p := 0) (q := 3) (r := 1) (s := 2)
      (by decide) (by decide) (by decide)
      (by decide) (by decide) (by decide) rfl rfl rfl rfl
      (cov4 (by decide) (by decide) (by decide) (by decide) (by decide)
        (by decide)) hc hzA

/-- Tex line 137: even-order elements of $A_4$ lie in the subgroup $V_4$. -/
theorem heven_a4 (z : ↥(alternatingGroup (Fin 4))) (hzo : (2 : ℕ) ∣ orderOf z) :
    z ∈ V4.subgroupOf (alternatingGroup (Fin 4)) := by
  obtain ⟨m, hm⟩ := hzo
  have hpos : 0 < m := by
    have h1 := orderOf_pos (x := z)
    omega
  have hy2 : z ^ m * z ^ m = 1 := by
    rw [← pow_add]
    have hexp : m + m = 2 * m := by ring
    rw [hexp, ← hm, pow_orderOf_eq_one]
  have hy1 : z ^ m ≠ 1 := by
    intro heq
    have hdvd := orderOf_dvd_of_pow_eq_one heq
    rw [hm] at hdvd
    have hle := Nat.le_of_dvd hpos hdvd
    omega
  have hy2' : ((z ^ m : ↥(alternatingGroup (Fin 4))).val : Perm (Fin 4)) *
      (z ^ m : ↥(alternatingGroup (Fin 4))).val = 1 :=
    congrArg Subtype.val hy2
  have hy1' : (z ^ m : ↥(alternatingGroup (Fin 4))).val ≠ 1 := fun hc =>
    hy1 (Subtype.ext hc)
  have hyV := involution_mem_V4
    (z ^ m : ↥(alternatingGroup (Fin 4))).property hy2' hy1'
  have hc1 : z * z ^ m = z ^ m * z := by rw [← pow_succ', ← pow_succ]
  have hc2 : (z : Perm (Fin 4)) * (z ^ m : ↥(alternatingGroup (Fin 4))).val =
      (z ^ m : ↥(alternatingGroup (Fin 4))).val * (z : Perm (Fin 4)) := by
    simpa using congrArg Subtype.val hc1
  have hzV := mem_V4_of_commute z.property hyV hy1' hc2
  exact Subgroup.mem_subgroupOf.mpr hzV

/-! ### The subgroup data of the generalized theorem -/

/-- $V_4$ (transported into $A_4$) is abelian: its four elements commute. -/
theorem hab_N (x y : ↥(alternatingGroup (Fin 4)))
    (hx : x ∈ V4.subgroupOf (alternatingGroup (Fin 4)))
    (hy : y ∈ V4.subgroupOf (alternatingGroup (Fin 4))) :
    x * y = y * x := by
  rcases mem_V4.mp (Subgroup.mem_subgroupOf.mp hx) with hx1 | hx1 | hx1 | hx1 <;>
    rcases mem_V4.mp (Subgroup.mem_subgroupOf.mp hy) with hy1 | hy1 | hy1 | hy1
  all_goals
    refine Subtype.ext ?_
    show (x : Perm (Fin 4)) * (y : Perm (Fin 4)) =
      (y : Perm (Fin 4)) * (x : Perm (Fin 4))
    rw [hx1, hy1] <;>
      (first
        | rfl
        | (rw [dt1_mul_dt2, dt2_mul_dt1])
        | (rw [dt1_mul_dt3, dt3_mul_dt1])
        | (rw [dt2_mul_dt3, dt3_mul_dt2]))

private theorem sign_dt1 : sign dt1 = 1 := by
  rw [show dt1 = swap 0 1 * swap 2 3 from rfl, sign_mul,
    sign_swap (show (0 : Fin 4) ≠ 1 by decide),
    sign_swap (show (2 : Fin 4) ≠ 3 by decide)]
  norm_num

private theorem sign_dt2 : sign dt2 = 1 := by
  rw [show dt2 = swap 0 2 * swap 1 3 from rfl, sign_mul,
    sign_swap (show (0 : Fin 4) ≠ 2 by decide),
    sign_swap (show (1 : Fin 4) ≠ 3 by decide)]
  norm_num

private theorem sign_dt3 : sign dt3 = 1 := by
  rw [show dt3 = swap 0 3 * swap 1 2 from rfl, sign_mul,
    sign_swap (show (0 : Fin 4) ≠ 3 by decide),
    sign_swap (show (1 : Fin 4) ≠ 2 by decide)]
  norm_num

/-- Conjugates of nontrivial $V_4$ elements stay in $V_4$: they are again
involutions of even sign, hence double transpositions. -/
private theorem mul_inv_conj_mem_V4 {g xv : Perm (Fin 4)} (hxv : xv ∈ V4)
    (hx2 : xv * xv = 1) (hx1 : xv ≠ 1) : g * xv * g⁻¹ ∈ V4 := by
  have hsq : (g * xv * g⁻¹) * (g * xv * g⁻¹) = 1 := by
    calc (g * xv * g⁻¹) * (g * xv * g⁻¹)
        = g * (xv * xv) * g⁻¹ := by group
      _ = g * 1 * g⁻¹ := by rw [hx2]
      _ = 1 := by simp
  have hne : g * xv * g⁻¹ ≠ 1 := by
    intro hh
    apply hx1
    calc xv = g⁻¹ * (g * xv * g⁻¹) * g := by group
      _ = g⁻¹ * 1 * g := by rw [hh]
      _ = 1 := by simp
  have hsgn : sign (g * xv * g⁻¹) = sign g * (sign xv * (sign g)⁻¹) := by
    rw [sign_mul, sign_mul, map_inv, mul_assoc]
  have hA : g * xv * g⁻¹ ∈ alternatingGroup (Fin 4) := by
    rw [mem_alternatingGroup, hsgn]
    rcases mem_V4.mp hxv with hx1' | hx1' | hx1' | hx1'
    · exact absurd hx1' hx1
    · rw [show xv = dt1 from hx1', sign_dt1]; group
    · rw [show xv = dt2 from hx1', sign_dt2]; group
    · rw [show xv = dt3 from hx1', sign_dt3]; group
  exact involution_mem_V4 hA hsq hne

/-- Normality of the transported $V_4$ inside $A_4$ (tex line 138: "$N$ is a
normal subgroup of $G$"). -/
theorem normal_N : Normal (V4.subgroupOf (alternatingGroup (Fin 4))) where
  conj_mem n hn g := by
    rw [Subgroup.mem_subgroupOf] at hn
    rw [Subgroup.mem_subgroupOf]
    show (g : Perm (Fin 4)) * (n : Perm (Fin 4)) * (g : Perm (Fin 4))⁻¹ ∈ V4
    rcases mem_V4.mp hn with hxv | hxv | hxv | hxv
    · rw [show (n : Perm (Fin 4)) = 1 from hxv]; simp
    · rw [show (n : Perm (Fin 4)) = dt1 from hxv]
      exact mul_inv_conj_mem_V4 (mem_V4.2 (Or.inr (Or.inl rfl))) dt1_sq
        dt1_ne_one
    · rw [show (n : Perm (Fin 4)) = dt2 from hxv]
      exact mul_inv_conj_mem_V4 (mem_V4.2 (Or.inr (Or.inr (Or.inl rfl)))) dt2_sq
        dt2_ne_one
    · rw [show (n : Perm (Fin 4)) = dt3 from hxv]
      exact mul_inv_conj_mem_V4 (mem_V4.2 (Or.inr (Or.inr (Or.inr rfl)))) dt3_sq
        dt3_ne_one

/-- Conjugation reaches every ordered pair of distinct nonidentity elements
of $V_4$ (tex line 139): powers of $(0\,1\,2)$ cycle the three double
transpositions. -/
theorem hconj_N (x y : ↥(alternatingGroup (Fin 4)))
    (hx : x ∈ V4.subgroupOf (alternatingGroup (Fin 4)))
    (hx1 : x ≠ 1) (hy : y ∈ V4.subgroupOf (alternatingGroup (Fin 4)))
    (hy1 : y ≠ 1) :
    ∃ t : ↥(alternatingGroup (Fin 4)), t⁻¹ * x * t = y := by
  have hxV : (x : Perm (Fin 4)) ∈ V4 := Subgroup.mem_subgroupOf.mp hx
  have hyV : (y : Perm (Fin 4)) ∈ V4 := Subgroup.mem_subgroupOf.mp hy
  rcases mem_V4.mp hxV with hxv | hxv | hxv | hxv
  · exact absurd (Subtype.ext hxv) hx1
  · rcases mem_V4.mp hyV with hyv | hyv | hyv | hyv
    · exact absurd (Subtype.ext hyv) hy1
    · refine ⟨⟨1, Subgroup.one_mem _⟩, ?_⟩
      exact Subtype.ext (by simpa using hxv.trans hyv.symm)
    · refine ⟨⟨cyc⁻¹ * cyc⁻¹, mem_a4_cyc2inv⟩, ?_⟩
      refine Subtype.ext ?_
      show ((cyc⁻¹ * cyc⁻¹ : Perm (Fin 4))⁻¹ * (x : Perm (Fin 4)) *
        (cyc⁻¹ * cyc⁻¹)) = (y : Perm (Fin 4))
      rw [hxv, hyv]
      calc ((cyc⁻¹ : Perm (Fin 4)) * cyc⁻¹)⁻¹ * dt1 * (cyc⁻¹ * cyc⁻¹)
          = cyc * cyc * dt1 * (cyc⁻¹ * cyc⁻¹) :=
            by rw [mul_inv_rev, inv_inv]
        _ = cyc * (cyc * dt1 * cyc⁻¹) * cyc⁻¹ := by group
        _ = cyc * dt3 * cyc⁻¹ := by rw [conj_cyc_dt1]
        _ = dt2 := conj_cyc_dt3
    · refine ⟨⟨cyc⁻¹, mem_a4_cyc_inv⟩, ?_⟩
      refine Subtype.ext ?_
      show ((cyc⁻¹ : Perm (Fin 4))⁻¹ * (x : Perm (Fin 4)) * cyc⁻¹) =
        (y : Perm (Fin 4))
      rw [hxv, hyv]
      exact conj_cyc_dt1
  · rcases mem_V4.mp hyV with hyv | hyv | hyv | hyv
    · exact absurd (Subtype.ext hyv) hy1
    · refine ⟨⟨cyc⁻¹, mem_a4_cyc_inv⟩, ?_⟩
      refine Subtype.ext ?_
      show ((cyc⁻¹ : Perm (Fin 4))⁻¹ * (x : Perm (Fin 4)) * cyc⁻¹) =
        (y : Perm (Fin 4))
      rw [hxv, hyv]
      exact conj_cyc_dt2
    · refine ⟨⟨1, Subgroup.one_mem _⟩, ?_⟩
      exact Subtype.ext (by simpa using hxv.trans hyv.symm)
    · refine ⟨⟨cyc⁻¹ * cyc⁻¹, mem_a4_cyc2inv⟩, ?_⟩
      refine Subtype.ext ?_
      show ((cyc⁻¹ * cyc⁻¹ : Perm (Fin 4))⁻¹ * (x : Perm (Fin 4)) *
        (cyc⁻¹ * cyc⁻¹)) = (y : Perm (Fin 4))
      rw [hxv, hyv]
      calc ((cyc⁻¹ : Perm (Fin 4)) * cyc⁻¹)⁻¹ * dt2 * (cyc⁻¹ * cyc⁻¹)
          = cyc * cyc * dt2 * (cyc⁻¹ * cyc⁻¹) :=
            by rw [mul_inv_rev, inv_inv]
        _ = cyc * (cyc * dt2 * cyc⁻¹) * cyc⁻¹ := by group
        _ = cyc * dt1 * cyc⁻¹ := by rw [conj_cyc_dt2]
        _ = dt3 := conj_cyc_dt1
  · rcases mem_V4.mp hyV with hyv | hyv | hyv | hyv
    · exact absurd (Subtype.ext hyv) hy1
    · refine ⟨⟨cyc⁻¹ * cyc⁻¹, mem_a4_cyc2inv⟩, ?_⟩
      refine Subtype.ext ?_
      show ((cyc⁻¹ * cyc⁻¹ : Perm (Fin 4))⁻¹ * (x : Perm (Fin 4)) *
        (cyc⁻¹ * cyc⁻¹)) = (y : Perm (Fin 4))
      rw [hxv, hyv]
      calc ((cyc⁻¹ : Perm (Fin 4)) * cyc⁻¹)⁻¹ * dt3 * (cyc⁻¹ * cyc⁻¹)
          = cyc * cyc * dt3 * (cyc⁻¹ * cyc⁻¹) :=
            by rw [mul_inv_rev, inv_inv]
        _ = cyc * (cyc * dt3 * cyc⁻¹) * cyc⁻¹ := by group
        _ = cyc * dt2 * cyc⁻¹ := by rw [conj_cyc_dt3]
        _ = dt1 := conj_cyc_dt2
    · refine ⟨⟨cyc⁻¹, mem_a4_cyc_inv⟩, ?_⟩
      refine Subtype.ext ?_
      show ((cyc⁻¹ : Perm (Fin 4))⁻¹ * (x : Perm (Fin 4)) * cyc⁻¹) =
        (y : Perm (Fin 4))
      rw [hxv, hyv]
      exact conj_cyc_dt3
    · refine ⟨⟨1, Subgroup.one_mem _⟩, ?_⟩
      exact Subtype.ext (by simpa using hxv.trans hyv.symm)

/-! ### The excluded factorization $(2,3,2)$ -/

/-- Sizes $(2,3,2)$ of tex line 223. -/
def sizes232 : Fin 3 → ℕ := ![2, 3, 2]

/-- Theorem `thm1` instantiated at $k = 3$ (tex lines 128-142), completing
Corollary 3.3 (tex lines 220-229): $A_4$ admits no factorization $(2,3,2)$. -/
theorem no_factorization_a4_two_three_two :
    ¬ ∃ A : Fin 3 → Set ↥(alternatingGroup (Fin 4)),
      IsFactorization A ∧ ∀ t, Nat.card (A t) = sizes232 t := by
  rintro ⟨A, hfac, hcard⟩
  exact no_factorization_with_small_ends normal_N hab_N heven_a4 hconj_N A hfac
    (by rw [hcard 0]; rfl) (by rw [hcard (Fin.last 2)]; rfl)

end McCulloch26_1.Cor33
