import McCulloch26_1.Basic
import McCulloch26_1.Lem_2_2_EndTranslate
import McCulloch26_1.Gaps

/-!
# Theorem 2.3 (`thm1`) of McCulloch26-1, generalized

The paper states (tex lines 132-142) that the Frobenius group of order
`2^(k-1) * (2^(k-1) - 1)` admits no k-fold factorization for the factorization
`(2, ..., 2, 2^(k-1) - 1, 2)`.

Two generalizations, both recorded in `status.md`:

* Only the two abstract properties of the group set up at tex line 128 are
  used: even-order elements are exactly the nonidentity elements of the
  normal subgroup `N`, and conjugation reaches every nonidentity element of
  `N` (transitivity of the complement action). Mathlib has no Frobenius group
  API, so the concrete instantiation stays a backlog row.
* The size of the middle sets is never used by the printed proof; only that
  the end sets have cardinality 2.

Source: /home/chz/src/gamskil/docs/arxiv/2607.20569v3/Some_Answers_Factorization.tex
lines 128-142.
-/

open Set

variable {G : Type*} [Group G]

/-- Dichotomy used twice in Theorem 2.3: a two-element set containing `1`
consists of `1` together with one further element `a ∈ s`, `a ≠ 1`. -/
theorem exists_complement_of_card_two {s : Set G} (h1 : (1 : G) ∈ s)
    (hc : Nat.card ↥s = 2) :
    ∃ a : G, a ∈ s ∧ a ≠ 1 ∧ ∀ z ∈ s, z = 1 ∨ z = a := by
  rw [Nat.card_coe_set_eq, Set.ncard_eq_two] at hc
  obtain ⟨p, q, hpq, hs⟩ := hc
  by_cases hx : p = 1
  · refine ⟨q, by rw [hs]; simp, ?_, ?_⟩
    · intro hq1
      apply hpq
      rw [hx, hq1]
    · intro z hz
      rw [hs] at hz
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
      rcases hz with h | h
      · exact Or.inl (h.trans hx)
      · exact Or.inr h
  · have hq1 : q = 1 := by
      have hm1 : (1 : G) ∈ s := h1
      rw [hs] at hm1
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hm1
      rcases hm1 with hc | hc
      · exact absurd hc.symm hx
      · exact hc.symm
    refine ⟨p, by rw [hs]; simp, hx, ?_⟩
    intro z hz
    rw [hs] at hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with h | h
    · exact Or.inr h
    · exact Or.inl (h.trans hq1)

/-- All four difference-set shapes of two-point ends land in the cyclic
subgroup generated by the nontrivial element. -/
theorem mem_zpowers_of_cases {a p q : G} (ha0p : p = 1 ∨ p = a)
    (ha0q : q = 1 ∨ q = a) : p⁻¹ * q ∈ Subgroup.zpowers a := by
  rcases ha0p with rfl | rfl <;> rcases ha0q with rfl | rfl <;> simp

/-- Same dichotomy for right-difference shape `p * q⁻¹` (last factor). -/
theorem mem_zpowers_of_casesR {a p q : G} (ha0p : p = 1 ∨ p = a)
    (ha0q : q = 1 ∨ q = a) : p * q⁻¹ ∈ Subgroup.zpowers a := by
  rcases ha0p with rfl | rfl <;> rcases ha0q with rfl | rfl <;> simp

/-- Core of Theorem 2.3 under the extra assumption that both end sets contain
the identity; the wrapper below removes it via Lemma 2.2 (tex line 125). -/
theorem no_factorization_with_small_ends_core
    {N : Subgroup G} (hN : N.Normal)
    (hab : ∀ x y : G, x ∈ N → y ∈ N → x * y = y * x)
    (heven : ∀ z : G, (2 : ℕ) ∣ orderOf z → z ∈ N)
    (hconj : ∀ x y : G, x ∈ N → x ≠ 1 → y ∈ N → y ≠ 1 → ∃ t : G, t⁻¹ * x * t = y)
    {n : ℕ} (A : Fin (n + 2) → Set G) (hfac : IsFactorization A)
    (h0 : Nat.card ↥(A 0) = 2) (hl : Nat.card ↥(A (Fin.last (n + 1))) = 2)
    (he0 : (1 : G) ∈ A 0) (hel : (1 : G) ∈ A (Fin.last (n + 1))) :
    False := by
  classical
  -- tex line 137: the ends are `{1, a}` and `{1, b}`
  obtain ⟨a, ha0mem, ha1, ha0⟩ := exists_complement_of_card_two he0 h0
  obtain ⟨b, hbmem, hb1, hbl⟩ := exists_complement_of_card_two hel hl
  -- gap divisibility (Lemma 2.1(i), tex lines 112-118) forces even order,
  -- hence membership in N ("A_1 and A_k are in fact subgroups of N")
  have haN : a ∈ N := by
    apply heven
    have hgap := card_dvd_card_closure_diffSet_first hfac
    rw [h0] at hgap
    have haclo : a ∈ Subgroup.closure (diffSet (A 0)) :=
      Subgroup.subset_closure ⟨(1, a), ⟨he0, ha0mem⟩, by group⟩
    have hsub : Subgroup.closure (diffSet (A 0)) ≤ Subgroup.zpowers a := by
      rw [Subgroup.closure_le]
      intro w hw
      unfold diffSet at hw
      obtain ⟨p, hp, hpval⟩ := hw
      rw [← hpval]
      exact mem_zpowers_of_cases (ha0 p.1 hp.1) (ha0 p.2 hp.2)
    have hcl : Subgroup.closure (diffSet (A 0)) = Subgroup.zpowers a :=
      le_antisymm hsub (Subgroup.zpowers_le.mpr haclo)
    rw [hcl, Nat.card_zpowers] at hgap
    exact hgap
  have hbN : b ∈ N := by
    apply heven
    have hgap := card_dvd_card_closure_diffSet_last hfac
    rw [hl] at hgap
    have hbclo : b ∈ Subgroup.closure (diffSetR (A (Fin.last (n + 1)))) :=
      Subgroup.subset_closure ⟨(b, 1), ⟨hbmem, hel⟩, by group⟩
    have hsub : Subgroup.closure (diffSetR (A (Fin.last (n + 1)))) ≤
        Subgroup.zpowers b := by
      rw [Subgroup.closure_le]
      intro w hw
      unfold diffSetR at hw
      obtain ⟨p, hp, hpval⟩ := hw
      rw [← hpval]
      exact mem_zpowers_of_casesR (hbl p.1 hp.1) (hbl p.2 hp.2)
    have hcl : Subgroup.closure (diffSetR (A (Fin.last (n + 1)))) =
        Subgroup.zpowers b :=
      le_antisymm hsub (Subgroup.zpowers_le.mpr hbclo)
    rw [hcl, Nat.card_zpowers] at hgap
    exact hgap
  -- tex line 139: S meets every coset of N, in the form z = s * nu
  have hcov : ∀ z : G, ∃ s ∈ setSeqProd (fun j : Fin n => A (Fin.castSucc j).succ),
      ∃ ν ∈ N, z = s * ν := by
    intro z
    obtain ⟨fz, hfzp, -⟩ := hfac z
    have hzS : z ∈ setSeqProd A := ⟨fz, hfzp⟩
    obtain ⟨c₀, y, c₁, hc0, hyS, hc1, hzy⟩ := setSeqProd_decomp hzS
    have c0N : c₀ ∈ N := by
      rcases ha0 c₀ hc0 with h | h
      · rw [h]; exact Subgroup.one_mem _
      · rw [h]; exact haN
    have c1N : c₁ ∈ N := by
      rcases hbl c₁ hc1 with h | h
      · rw [h]; exact Subgroup.one_mem _
      · rw [h]; exact hbN
    refine ⟨y, hyS, y⁻¹ * c₀ * y * c₁,
      Subgroup.mul_mem _ (Subgroup.Normal.conj_mem' hN c₀ c0N y) c1N, ?_⟩
    rw [hzy]; group
  -- tex lines 139-140: transitivity gives an s in S conjugating a to b
  obtain ⟨t, ht⟩ := hconj a b haN ha1 hbN hb1
  obtain ⟨s, hsS, ν, hνN, hst⟩ := hcov t
  have key : s⁻¹ * a * s = b := by
    calc s⁻¹ * a * s = ν * (t⁻¹ * a * t) * ν⁻¹ := by rw [hst]; group
      _ = ν * b * ν⁻¹ := by rw [ht]
      _ = b := by rw [hab ν b hνN hbN]; group
  have asym : a * s = s * b := by
    calc a * s = s * (s⁻¹ * a * s) := by group
      _ = s * b := by rw [key]
  -- tex line 141: two distinct representations of one element
  obtain ⟨fm, hfm⟩ := hsS
  set u₁ : Fin (n + 2) → G := fun i =>
    if h : i.val = 0 then a
    else if h' : i.val = n + 1 then 1
    else fm ⟨i.val - 1, by have := i.isLt; omega⟩ with hu₁def
  set u₂ : Fin (n + 2) → G := fun i =>
    if h : i.val = 0 then 1 else if h' : i.val = n + 1 then b
    else fm ⟨i.val - 1, by have := i.isLt; omega⟩ with hu₂def
  have hF0₁ : u₁ 0 = a := by rw [hu₁def]; exact dif_pos rfl
  have hF0₂ : u₂ 0 = 1 := by rw [hu₂def]; exact dif_pos rfl
  have hFl₁ : u₁ (Fin.last (n + 1)) = 1 := by
    rw [hu₁def]
    exact dif_pos (Fin.val_last (n + 1))
  have hFl₂ : u₂ (Fin.last (n + 1)) = b := by
    rw [hu₂def]
    exact dif_pos (Fin.val_last (n + 1))
  have hmid : ∀ j : Fin n, u₁ (Fin.castSucc j).succ = fm j ∧
      u₂ (Fin.castSucc j).succ = fm j := by
    intro j
    have hj := j.isLt
    have hcv : ((Fin.castSucc j).succ : ℕ) = j.val + 1 := rfl
    have hd0 : ¬(((Fin.castSucc j).succ : Fin (n + 2)).val = 0) := by omega
    have hd1 : ¬(((Fin.castSucc j).succ : Fin (n + 2)).val = n + 1) := by omega
    rw [hu₁def, hu₂def]
    simp only []
    rw [dif_neg hd0, dif_neg hd0, dif_neg hd1, dif_neg hd1]
    exact ⟨rfl, rfl⟩
  have hFm₁ : ∀ j : Fin n, u₁ (Fin.castSucc j).succ = fm j := fun j => (hmid j).1
  have hFm₂ : ∀ j : Fin n, u₂ (Fin.castSucc j).succ = fm j := fun j => (hmid j).2
  have hu₁mem : ∀ i, u₁ i ∈ A i := by
    intro i
    by_cases h0 : i.val = 0
    · have hi0 : i = 0 := Fin.ext h0
      rw [hi0, hF0₁]; exact ha0mem
    · by_cases hl' : i.val = n + 1
      · have hil : i = Fin.last (n + 1) := Fin.ext hl'
        rw [hil, hFl₁]; exact hel
      · have hjlt : i.val < n + 2 := i.isLt
        have hpos1 : 0 < i.val := Nat.pos_of_ne_zero h0
        obtain ⟨j, hij⟩ : ∃ j : Fin n, i = (Fin.castSucc j).succ :=
          ⟨⟨i.val - 1, by have := i.isLt; omega⟩,
            Fin.ext (by simp; omega)⟩
        subst hij
        have hm := hmid j
        show u₁ (Fin.castSucc j).succ ∈ A (Fin.castSucc j).succ
        rw [hm.1]
        exact (fm j).2
  have hu₂mem : ∀ i, u₂ i ∈ A i := by
    intro i
    by_cases h0 : i.val = 0
    · have hi0 : i = 0 := Fin.ext h0
      rw [hi0, hF0₂]; exact he0
    · by_cases hl' : i.val = n + 1
      · have hil : i = Fin.last (n + 1) := Fin.ext hl'
        rw [hil, hFl₂]; exact hbmem
      · have hjlt : i.val < n + 2 := i.isLt
        have hpos1 : 0 < i.val := Nat.pos_of_ne_zero h0
        obtain ⟨j, hij⟩ : ∃ j : Fin n, i = (Fin.castSucc j).succ :=
          ⟨⟨i.val - 1, by have := i.isLt; omega⟩,
            Fin.ext (by simp; omega)⟩
        subst hij
        have hm := hmid j
        show u₂ (Fin.castSucc j).succ ∈ A (Fin.castSucc j).succ
        rw [hm.2]
        exact (fm j).2
  have e1 : (List.ofFn u₁).prod = a * s := by
    rw [prod_first_mid_last, hF0₁, hFl₁]
    have hX : (List.ofFn fun j : Fin n => u₁ (Fin.castSucc j).succ).prod = s := by
      simpa only [hFm₁] using hfm
    rw [hX, mul_one]
  have e2 : (List.ofFn u₂).prod = s * b := by
    rw [prod_first_mid_last, hF0₂, hFl₂]
    have hX : (List.ofFn fun j : Fin n => u₂ (Fin.castSucc j).succ).prod = s := by
      simpa only [hFm₂] using hfm
    rw [hX, one_mul]
  obtain ⟨f₀, hf₀p, hf₀u⟩ := hfac (a * s)
  apply ha1
  have r1 : (fun i => ⟨u₁ i, hu₁mem i⟩) = f₀ :=
    hf₀u (fun i => ⟨u₁ i, hu₁mem i⟩) e1
  have r2 : (fun i => ⟨u₂ i, hu₂mem i⟩) = f₀ :=
    hf₀u (fun i => ⟨u₂ i, hu₂mem i⟩) (e2.trans asym.symm)
  exact congrArg Subtype.val (congrFun (r1.trans r2.symm) 0)

/-- Theorem 2.3 (`thm1`), tex lines 132-142, generalized as described in the
module docstring: a finite group whose even-order elements are exactly the
nonidentity elements of a normal subgroup `N`, with conjugation transitive on
`N \ {e}`, admits no factorization into at least two sets whose end sets have
cardinality `2`. The paper applies this to the Frobenius group of order
`2^(k-1) * (2^(k-1) - 1)` with `(2, ..., 2, 2^(k-1) - 1, 2)` for `k ≥ 3`
(tex lines 128-133); note `hab` follows there from `N` being elementary
abelian, and the middle size `2^(k-1) - 1` is forced but never used. -/
theorem no_factorization_with_small_ends
    {N : Subgroup G} (hN : N.Normal)
    (hab : ∀ x y : G, x ∈ N → y ∈ N → x * y = y * x)
    (heven : ∀ z : G, (2 : ℕ) ∣ orderOf z → z ∈ N)
    (hconj : ∀ x y : G, x ∈ N → x ≠ 1 → y ∈ N → y ≠ 1 → ∃ t : G, t⁻¹ * x * t = y)
    {n : ℕ} (A : Fin (n + 2) → Set G) (hfac : IsFactorization A)
    (h0 : Nat.card ↥(A 0) = 2) (hl : Nat.card ↥(A (Fin.last (n + 1))) = 2) :
    False := by
  classical
  have hne0 : Nonempty ↥(A 0) := by
    by_contra hc
    rw [not_nonempty_iff] at hc
    have : Nat.card ↥(A 0) = 0 := Finite.card_eq_zero_iff.mpr hc
    omega
  have hnel : Nonempty ↥(A (Fin.last (n + 1))) := by
    by_contra hc
    rw [not_nonempty_iff] at hc
    have : Nat.card ↥(A (Fin.last (n + 1))) = 0 := Finite.card_eq_zero_iff.mpr hc
    omega
  obtain ⟨c, hcA⟩ := hne0
  obtain ⟨d, hdA⟩ := hnel
  have hbfac : IsFactorization (endTranslate c⁻¹ d⁻¹ A) :=
    isFactorization_endTranslate c⁻¹ d⁻¹ A hfac
  have hm0 : (1 : G) ∈ endTranslate c⁻¹ d⁻¹ A 0 := by
    rw [endTranslate_apply_zero]
    exact ⟨c, hcA, by group⟩
  have hml : (1 : G) ∈ endTranslate c⁻¹ d⁻¹ A (Fin.last (n + 1)) := by
    rw [endTranslate_apply_last]
    exact ⟨d, hdA, by group⟩
  have hB0 : Nat.card ↥(endTranslate c⁻¹ d⁻¹ A 0) = 2 := by
    rw [card_endTranslate_zero]; exact h0
  have hBl : Nat.card ↥(endTranslate c⁻¹ d⁻¹ A (Fin.last (n + 1))) = 2 := by
    rw [card_endTranslate_last]; exact hl
  exact no_factorization_with_small_ends_core hN hab heven hconj _ hbfac hB0 hBl hm0 hml
